CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vk_id BIGINT NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    role ENUM('Арендатор', 'Заведующий') NOT NULL DEFAULT 'Арендатор',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
